### ISSUE TITLE
Need to document how to get env vars into ZEIT

### ISSUE THREAD

**Issue by bencooper222** [gfting/anon-feedback-slackbot#1]
Zeit's env var process sucks. You should document how it works because it's super confusing.

**Comment by gfting** [comment]
Thanks @bencooper222 , I added some more information in the README. Let me know if it's not what you quite wanted–I just followed the syntax of having to export a single env var.

**Comment by gfting** [comment]
@bencooper222 are you fine with the documentation as is now? I'll close the issue if that's the case.

**Comment by bencooper222** [comment]
lgtm!
